# Generated by Django 4.1.4 on 2023-07-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Q_app", "0002_remove_requirements_planned_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="requirements",
            name="client_access",
            field=models.CharField(default="[]", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="requirements",
            name="planned_budget_clicks",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="requirements",
            name="planned_budget_impressions",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="requirements",
            name="planned_budget_sessions",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
